### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by weiQiangGe** [uncleguanghui/pyflink_learn#16]
您好，请问一下。我在学习案例4_window的时候，本机执行stream12.py可以成功运行，而提交到flink环境时，连接kafka源那块报错 “”“” syntaxError: invalid syntax。flink 版本为1.12， python版本为3.65。期待您的回答，谢谢！

**Comment by uncleguanghui** [comment]
可参考 https://blog.csdn.net/qq_42719751/article/details/102535051 ，看看是否是环境/路径等问题

**Comment by H4Njx** [comment]
> 可参考 https://blog.csdn.net/qq_42719751/article/details/102535051 ，看看是否是环境/路径等问题

跟这个人一样的问题 
运行代码是
/opt/flink-1.12.2/bin/flink run -m localhost:8081 -pyexec /usr/local/python3/bin/python3.7 -py aiops_windows.py

报错为
  File "aiops_windows.py", line 82
    """)
      ^
SyntaxError: invalid syntax
org.apache.flink.client.program.ProgramAbortException
        at org.apache.flink.client.python.PythonDriver.main(PythonDriver.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:349)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:219)
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
        at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
        at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
